first commit changed rootstrap template
FedericoChavazza/Movie-App pull request #1
Opened 2022-03-28 16:56 UTC by FedericoChavazza

## Links:

https://trello.com/c/AJpJEw5S/3-add-first-commit-removing-login-and-other-unnecessary-features

## What & Why:

Changed template to start app

## Risks, Mitigation & Rollback:

- [x] Safe to Revert *check this box if this PR can be reverted without incident*

2022-03-29 12:46 UTC, JulianPasquale commented on src/services/endpoints/movieEndpoints.js
> +import endpoints from 'constants/endpoints';
We should not include code related to movies and its endpoints in this PR. This should be done later, not as part of this Trello card

2022-03-29 12:48 UTC, JulianPasquale requested changes
Can you also improve the PR description? Please add details about what is being removed here

2022-03-29 15:13 UTC, FedericoChavazza commented on src/services/endpoints/movieEndpoints.js
> +import endpoints from 'constants/endpoints';
So I just delete the whole redux file? I though that it was like "boceto" kind of design, and I prefer not doing the whole redux system again, since the template's flow is weird.

2022-03-29 17:06 UTC, JulianPasquale commented on src/services/endpoints/movieEndpoints.js
> +import endpoints from 'constants/endpoints';
But this is a new file you're adding, why deleting it can cause any issue?

2022-03-29 17:07 UTC, JulianPasquale commented on src/services/endpoints/movieEndpoints.js
> +import endpoints from 'constants/endpoints';
I didn't say you should remove the redux file, just avoid any reference to movies endpoints at this point

2022-03-29 21:37 UTC, FedericoChavazza commented on src/services/endpoints/movieEndpoints.js
> +import endpoints from 'constants/endpoints';
AHHHHHHHHHHHH ok okok i get it now heehe

2022-03-30 12:16 UTC, JulianPasquale commented on src/state/slices/slice.js
> +import { createSlice } from '@reduxjs/toolkit';
Can you explain me the purpose of this file? Is really needed at this moment?

2022-03-30 15:07 UTC, JulianPasquale approved these changes

2022-03-31 15:04 UTC, martoesses reviewed
Good Job!!!, Here are some questions and suggestions to implement

2022-03-31 15:04 UTC, martoesses commented on src/services/api.js
> +import { createApi } from '@reduxjs/toolkit/dist/query';
why you change '@reduxjs/toolkit/query/react' for '@reduxjs/toolkit/dist/query'?
I would like to know what are a differences

2022-03-31 15:04 UTC, martoesses commented on src/services/api.js
> -import { baseQueryWithReauth } from 'utils/customQueries';
I think that utils/customQueries is a good solution to use calls to external apis.

2022-03-31 15:22 UTC, FedericoChavazza commented on src/services/api.js
> +import { createApi } from '@reduxjs/toolkit/dist/query';
AA autoimports, i didn't know, thanks!

2022-03-31 15:26 UTC, FedericoChavazza commented on src/services/api.js
> -import { baseQueryWithReauth } from 'utils/customQueries';
I wanted to use fetchBaseQuery who works the same, and saves you from having more code

2022-04-01 13:17 UTC, closed without merging