homeview with styles working
FedericoChavazza/Movie-App pull request #2
Opened 2022-03-28 20:46 UTC by FedericoChavazza

## Links:

https://trello.com/c/fxAvXdob/1-users-can-see-the-homepage-carousel

## What & Why:

it does show everything on the home view, buttons missing, but it works when scrolling

![image](https://user-images.githubusercontent.com/81062792/160483979-47d6fa69-1991-4474-815a-17ae9dae4ede.png)

## Risks, Mitigation & Rollback:

- [x] Safe to Revert *check this box if this PR can be reverted without incident*

2022-03-29 12:58 UTC, JulianPasquale commented on src/components/logicComponents/Carousel.js
> +export function Carousel({ mock }) {
Can avoid using `mock` as a prop here? For this component is actually not relevant if it is mock or real data.

I'd recommend you to use a more realistic name for the prop, and since the mock data is being passed from the parent, we'll avoid further naming changes

2022-03-29 12:58 UTC, JulianPasquale commented on src/components/routes/PrivateRoute.js
> +const PrivateRoute = ({ children, exact = false, path }) => {
Why do you need this component? Are you using it right now?

2022-03-29 12:58 UTC, JulianPasquale commented on src/components/logicComponents/styles.css
> +.Carousel-container {
In the [google doc](https://docs.google.com/document/d/1eMeZ8pdnoH6TILkMdLzh5T76B1MCqdZ5IPy5-UjBdnQ/edit?usp=sharing) with the app and technologies definition we defined that you should use SASS for styles

2022-03-29 12:58 UTC, JulianPasquale commented on src/locales/en.json
> +    "pageTitle": "RS React Redux Base"
```suggestion
    "pageTitle": "Movies App"
```

2022-03-29 12:58 UTC, JulianPasquale commented on src/pages/Home/Homepage.js
> +          {' '}
Why is this needed?

2022-03-29 12:58 UTC, JulianPasquale commented on src/state/store/configureStore.dev.js
> +import { api } from 'services/endpoints/movieEndpoints';
We are still not making any API request. Let's keep it clean without any reference to APIs

2022-03-29 16:12 UTC, FedericoChavazza commented on src/components/logicComponents/Carousel.js
> +export function Carousel({ mock }) {
Changed!

2022-03-29 16:12 UTC, FedericoChavazza commented on src/components/routes/PrivateRoute.js
> +const PrivateRoute = ({ children, exact = false, path }) => {
Oops, somehow I didn't realize, mb

2022-03-29 16:12 UTC, FedericoChavazza commented on src/components/logicComponents/styles.css
> +.Carousel-container {
Done, I felt in love with sass

2022-03-29 16:12 UTC, FedericoChavazza commented on src/locales/en.json
> +    "pageTitle": "RS React Redux Base"
Changed

2022-03-29 16:14 UTC, FedericoChavazza commented on src/pages/Home/Homepage.js
> +          {' '}
For the padding out of the scroll container, if that's not there, the only one container growing with padding is gonna be the actual scroll container, its gonna get bigger and worse :(

2022-03-29 16:15 UTC, FedericoChavazza commented on src/state/store/configureStore.dev.js
> +import { api } from 'services/endpoints/movieEndpoints';
I think is necessary to keep this without deleting, the flow is already done, it would be a shame if i just delete all of it

2022-03-29 17:09 UTC, JulianPasquale commented on src/pages/Home/Homepage.js
> +          {' '}
And why don't you use `padding` with css/sass? I feel that's is way better than this

2022-03-29 17:10 UTC, JulianPasquale commented on src/state/store/configureStore.dev.js
> +import { api } from 'services/endpoints/movieEndpoints';
I strongly believe we should not add any reference to movies endpoints yet.

2022-03-29 21:34 UTC, FedericoChavazza commented on src/state/store/configureStore.dev.js
> +import { api } from 'services/endpoints/movieEndpoints';
ok! gonna delete it here and in the other PRs

2022-03-29 21:46 UTC, FedericoChavazza commented on src/pages/Home/Homepage.js
> +          {' '}
wait, you mean the "{'  '}"?? idk why it does it the prettier by itself, doesnt change anything tho

2022-03-30 12:10 UTC, JulianPasquale commented on src/pages/Home/Homepage.js
> +          {' '}
yeah, I was talking about that. Sounds good then

2022-03-30 12:11 UTC, JulianPasquale commented on src/state/store/configureStore.dev.js
> +import { api } from 'services/endpoints/reduxEndpoints';
Can we keep this unchanged?

2022-03-30 12:14 UTC, JulianPasquale commented on src/state/reducer.js
> +  reducer: slice,
Why do we need this reducer here? Are we reading some data from Redux?

2022-03-30 12:14 UTC, JulianPasquale commented on src/styles/styles.css
> +body::-webkit-scrollbar {
Should we change this file extension to `scss`?

2022-03-30 12:14 UTC, JulianPasquale commented on src/components/viewComponents/styles.css.map
> +{
Seems like this file was generated when compiling the `scss` files right? I'm not sure but feels like this should not be versioned in the repo, can you confirm that with the team and maybe adding this to `.gitignore`?

2022-03-31 13:48 UTC, FedericoChavazza commented on src/state/store/configureStore.dev.js
> +import { api } from 'services/endpoints/reduxEndpoints';
done

2022-03-31 13:48 UTC, FedericoChavazza commented on src/state/reducer.js
> +  reducer: slice,
deleted!

2022-03-31 13:48 UTC, FedericoChavazza commented on src/components/viewComponents/styles.css.map
> +{
done too!

2022-03-31 15:21 UTC, martoesses commented on src/components/common/Button/styles.scss
> +  font-size: 18px;
My suggestion is to use rem instead of px

2022-03-31 15:21 UTC, martoesses commented on src/state/slices/slice.js
> +export default slice.reducer;
I think there is no need to create a slice at this point. When the time comes I think it should not be a global slice but a movieSlice for example.

2022-03-31 17:11 UTC, JulianPasquale requested changes

2022-03-31 17:11 UTC, JulianPasquale commented on src/components/viewComponents/Movie.js
> +  console.log(`${process.env.REACT_APP_IMG_URL}${img} `);
👀

2022-03-31 17:11 UTC, JulianPasquale commented on src/constants/endpoints.js
> +  discover: '/discover/movie',
This should not be here. We are still using mock data

2022-03-31 17:11 UTC, JulianPasquale commented on src/services/api.js
> +export const api = createApi({
hmm I though we were not going to use any endpoint... this task is just for the UI without any real information 😢

2022-03-31 17:26 UTC, FedericoChavazza commented
I gonna teach the computer how to fly

2022-03-31 18:53 UTC, JulianPasquale commented on src/components/viewComponents/styles.css.map
> +{
Check this again, seems like this file is still being versioned by Git

2022-03-31 18:53 UTC, JulianPasquale commented on src/components/viewComponents/styles.css
> +.Movie-container {
Shouldn't we use `scss` here?

2022-03-31 18:53 UTC, JulianPasquale commented on src/styles/variables.css.map
> +{
Same here about this `css.map` file. Should not be part of the github repo

2022-03-31 19:20 UTC, FedericoChavazza commented on src/components/viewComponents/styles.css
> +.Movie-container {
when you create a scss file and you use Watch SASS like i did, it creates an extra css and css.map file, thats why those files keep appearing even tho i already have a scss file

2022-03-31 19:22 UTC, FedericoChavazza commented on src/styles/variables.css.map
> +{
im searching, it seems that it didn't ignore css.map files as i asked, if u want i can just delete these files with the Watch SASS, to stop creating this ones randomly

2022-03-31 21:16 UTC, JulianPasquale commented on src/components/viewComponents/styles.css
> +.Movie-container {
So I guess this should also be ignored as `.css.map` files

2022-04-01 13:43 UTC, JulianPasquale approved these changes

2022-04-01 13:47 UTC, martoesses approved these changes

2022-04-01 13:47 UTC, martoesses commented on src/index.css
> +  font-size: 10px;
remember to use rem unit

2022-04-01 13:50 UTC, merged